import './sass/index.scss';
import './js/apiServiceMovies';
import './js/renderFilms';
import './js/loader'
import './js/onSearchByName';
import './js/renderMovieCardsToLibriary';
import './js/pagination';
import './js/scrolled';
import './js/modalTeam';
import './js/addMovieToLibriary';
import './js/modalFilm';
import './js/onGalleryItemClick';
import './js/onSearchLibrary';
